#!/usr/bin/env bash
# Brings up QuestDB, InfluxDB and Grafana locally, seeds synthetic vessel
# data into both, and checks that every provisioned panel draws something.
# One command to see the dashboards without being aboard.
#
# The dashboards read QuestDB; InfluxDB is still seeded because the boat's
# own bucket is still there for ad-hoc Flux exploration, and the two seeders
# share their value ranges.
#
#   scripts/dev_stack.sh up       # start, seed, verify
#   scripts/dev_stack.sh verify   # re-run the panel check only
#   scripts/dev_stack.sh seed     # re-seed only
#   scripts/dev_stack.sh logs     # follow grafana logs
#   scripts/dev_stack.sh down     # stop and delete the volumes
#
# Writes .env if absent, with throwaway credentials. That file is gitignored;
# it is not, and must not become, the boat's .env -- render.py owns that one.
# If .env already exists this script leaves it alone and assumes it is
# already pointed somewhere sensible.
#
# Only starts questdb, influxdb and grafana. The signalk, caddy and dex
# services in docker-compose.yml are not needed to look at a dashboard, and
# signalk in particular wants hardware this machine does not have.
set -euo pipefail

cd "$(dirname "$0")/.."

GRAFANA_URL="${GRAFANA_URL:-http://localhost:3001}"
INFLUX_URL_LOCAL="${INFLUX_URL_LOCAL:-http://localhost:8086}"
QUESTDB_URL_LOCAL="${QUESTDB_URL_LOCAL:-http://localhost:9000}"
DEV_TOKEN="dev-token-not-a-secret-0123456789"
DEV_ADMIN_PASSWORD="devadmin"

write_env_if_absent() {
	if [ -f .env ]; then
		echo "using existing .env"
		return
	fi
	echo "writing a development .env (throwaway credentials)"
	cat > .env <<-EOF
		# Generated by scripts/dev_stack.sh for local development.
		# Throwaway credentials. Not the boat's .env -- that one is rendered
		# from sops by scripts/render.py.
		DOCKER_INFLUXDB_INIT_MODE=setup
		DOCKER_INFLUXDB_INIT_USERNAME=dev
		DOCKER_INFLUXDB_INIT_PASSWORD=devpassword123
		DOCKER_INFLUXDB_INIT_ORG=symphony
		DOCKER_INFLUXDB_INIT_BUCKET=signalk
		DOCKER_INFLUXDB_INIT_RETENTION=30d
		DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DEV_TOKEN}

		INFLUX_TOKEN=${DEV_TOKEN}
		INFLUX_URL=http://influxdb:8086
		INFLUX_ORG=symphony
		INFLUX_BUCKET=signalk

		TELEGRAF_INFLUX_TOKEN=${DEV_TOKEN}
		TELEGRAF_INFLUX_ORG=symphony
		TELEGRAF_INFLUX_BUCKET=telegraf

		# QuestDB's shipped PGWire defaults; compose-questdb.yml overrides
		# neither. Grafana reaches it over symphony-net, not the published
		# loopback port.
		QUESTDB_HOST=questdb
		QUESTDB_PORT=8812
		QUESTDB_USER=admin
		QUESTDB_PASSWORD=quest

		GF_SECURITY_ADMIN_USER=admin
		GF_SECURITY_ADMIN_PASSWORD=${DEV_ADMIN_PASSWORD}

		# No OIDC locally: dex is a boat service and this stack has no issuer.
		GF_AUTH_GENERIC_OAUTH_ENABLED=false

		DOMAIN=example.invalid
		ACME_EMAIL=dev@example.invalid
		CLOUDFLARE_API_TOKEN=unused
		GF_SERVER_ROOT_URL=${GRAFANA_URL}
	EOF
}

wait_for() {
	local name="$1" url="$2" tries="${3:-60}"
	printf 'waiting for %s' "$name"
	for _ in $(seq 1 "$tries"); do
		if curl -fsS -o /dev/null "$url" 2>/dev/null; then
			printf ' ready\n'
			return 0
		fi
		printf '.'
		sleep 2
	done
	printf ' TIMED OUT\n'
	return 1
}

token_from_env() {
	grep -E '^INFLUX_TOKEN=' .env | head -1 | cut -d= -f2-
}

password_from_env() {
	grep -E '^GF_SECURITY_ADMIN_PASSWORD=' .env | head -1 | cut -d= -f2-
}

cmd_up() {
	write_env_if_absent
	python3 scripts/build_dashboards.py
	docker compose up -d questdb influxdb grafana

	# Every step below reports its own failure and then carries on, so that
	# the Grafana URL still gets printed: a stack that is up with one panel
	# empty is worth opening, and the exit status carries the bad news.
	local failed=0

	# /exec, not /status: QuestDB serves /status, /health and /metrics only
	# on its separate "min" server (9003), which compose-questdb.yml does not
	# publish. Measured on the pinned digest (QuestDB 10.0.0) -- /status on
	# 9000 is a 404, which curl -f treats as down, so this waited out the
	# full timeout and then aborted `up`.
	wait_for QuestDB "${QUESTDB_URL_LOCAL}/exec?query=select+1" || failed=1
	wait_for InfluxDB "${INFLUX_URL_LOCAL}/health" || failed=1
	wait_for Grafana "${GRAFANA_URL}/api/health" || failed=1
	cmd_seed || { echo "seeding did not complete -- see above"; failed=1; }
	cmd_verify || { echo "panel check did not pass -- see above"; failed=1; }

	echo
	echo "Grafana:  ${GRAFANA_URL}   admin / $(password_from_env)"
	echo "Dashboards are in the 'Marine' folder."
	return "$failed"
}

cmd_seed() {
	# Buckets are created on demand and picked per measurement by the same
	# routing the dashboards use, so this covers signalk, telegraf and
	# influxdb without naming them here.
	python3 scripts/seed_dev_influx.py \
		--url "${INFLUX_URL_LOCAL}" \
		--token "$(token_from_env)" \
		--org symphony
	python3 scripts/seed_dev_questdb.py --url "${QUESTDB_URL_LOCAL}"
}

cmd_verify() {
	python3 scripts/verify_dashboards_live.py \
		--grafana "${GRAFANA_URL}" \
		--user admin --password "$(password_from_env)" --quiet
}

cmd_down() {
	docker compose down -v
}

cmd_logs() {
	docker compose logs -f grafana
}

case "${1:-up}" in
	up) cmd_up ;;
	seed) cmd_seed ;;
	verify) cmd_verify ;;
	down) cmd_down ;;
	logs) cmd_logs ;;
	*)
		echo "usage: $0 {up|seed|verify|down|logs}" >&2
		exit 2
		;;
esac
