#!/usr/bin/env bash
# Brings up InfluxDB and Grafana locally, seeds synthetic vessel data, and
# checks that every provisioned panel draws something. One command to see the
# dashboards without being aboard.
#
#   scripts/dev_stack.sh up       # start, seed, verify
#   scripts/dev_stack.sh verify   # re-run the panel check only
#   scripts/dev_stack.sh seed     # re-seed only
#   scripts/dev_stack.sh logs     # follow grafana logs
#   scripts/dev_stack.sh down     # stop and delete the volumes
#
# Writes .env if absent, with throwaway credentials. That file is gitignored;
# it is not, and must not become, the boat's .env -- render.py owns that one.
# If .env already exists this script leaves it alone and assumes it is
# already pointed somewhere sensible.
#
# Only starts influxdb and grafana. The signalk, caddy and dex services in
# docker-compose.yml are not needed to look at a dashboard, and signalk in
# particular wants hardware this machine does not have.
set -euo pipefail

cd "$(dirname "$0")/.."

GRAFANA_URL="${GRAFANA_URL:-http://localhost:3001}"
INFLUX_URL_LOCAL="${INFLUX_URL_LOCAL:-http://localhost:8086}"
DEV_TOKEN="dev-token-not-a-secret-0123456789"
DEV_ADMIN_PASSWORD="devadmin"

write_env_if_absent() {
	if [ -f .env ]; then
		echo "using existing .env"
		return
	fi
	echo "writing a development .env (throwaway credentials)"
	cat > .env <<-EOF
		# Generated by scripts/dev_stack.sh for local development.
		# Throwaway credentials. Not the boat's .env -- that one is rendered
		# from sops by scripts/render.py.
		DOCKER_INFLUXDB_INIT_MODE=setup
		DOCKER_INFLUXDB_INIT_USERNAME=dev
		DOCKER_INFLUXDB_INIT_PASSWORD=devpassword123
		DOCKER_INFLUXDB_INIT_ORG=symphony
		DOCKER_INFLUXDB_INIT_BUCKET=signalk
		DOCKER_INFLUXDB_INIT_RETENTION=30d
		DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DEV_TOKEN}

		INFLUX_TOKEN=${DEV_TOKEN}
		INFLUX_URL=http://influxdb:8086
		INFLUX_ORG=symphony
		INFLUX_BUCKET=signalk

		TELEGRAF_INFLUX_TOKEN=${DEV_TOKEN}
		TELEGRAF_INFLUX_ORG=symphony
		TELEGRAF_INFLUX_BUCKET=telegraf

		GF_SECURITY_ADMIN_USER=admin
		GF_SECURITY_ADMIN_PASSWORD=${DEV_ADMIN_PASSWORD}

		# No OIDC locally: dex is a boat service and this stack has no issuer.
		GF_AUTH_GENERIC_OAUTH_ENABLED=false

		DOMAIN=example.invalid
		ACME_EMAIL=dev@example.invalid
		CLOUDFLARE_API_TOKEN=unused
		GF_SERVER_ROOT_URL=${GRAFANA_URL}
	EOF
}

wait_for() {
	local name="$1" url="$2" tries="${3:-60}"
	printf 'waiting for %s' "$name"
	for _ in $(seq 1 "$tries"); do
		if curl -fsS -o /dev/null "$url" 2>/dev/null; then
			printf ' ready\n'
			return 0
		fi
		printf '.'
		sleep 2
	done
	printf ' TIMED OUT\n'
	return 1
}

token_from_env() {
	grep -E '^INFLUX_TOKEN=' .env | head -1 | cut -d= -f2-
}

password_from_env() {
	grep -E '^GF_SECURITY_ADMIN_PASSWORD=' .env | head -1 | cut -d= -f2-
}

require_grafana_provisioning() {
	# compose-grafana.yml bind-mounts ./grafana/provisioning. If that path is
	# missing -- e.g. this script is running from a worktree or scratch
	# checkout that hasn't populated tracked files yet -- dockerd (root)
	# silently creates it as root:root before the container starts. That
	# root-owned stub then survives the worktree being torn down and blocks
	# every later Claude Code session sharing this uid's tmpdir. Fail loudly
	# here instead.
	if [ ! -d grafana/provisioning ] || [ -z "$(find grafana/provisioning -type f -print -quit)" ]; then
		echo "error: grafana/provisioning is missing or empty at $(pwd)/grafana/provisioning" >&2
		echo "refusing to run 'docker compose up' -- the bind mount source must" >&2
		echo "already exist and be populated (git checkout), or dockerd will" >&2
		echo "auto-create it as root and break local Claude Code sessions." >&2
		exit 1
	fi
}

cmd_up() {
	write_env_if_absent
	require_grafana_provisioning
	python3 scripts/build_dashboards.py
	docker compose up -d influxdb grafana
	wait_for InfluxDB "${INFLUX_URL_LOCAL}/health"
	wait_for Grafana "${GRAFANA_URL}/api/health"
	cmd_seed
	cmd_verify
	echo
	echo "Grafana:  ${GRAFANA_URL}   admin / $(password_from_env)"
	echo "Dashboards are in the 'Marine' folder."
}

cmd_seed() {
	# Buckets are created on demand and picked per measurement by the same
	# routing the dashboards use, so this covers signalk, telegraf and
	# influxdb without naming them here.
	python3 scripts/seed_dev_influx.py \
		--url "${INFLUX_URL_LOCAL}" \
		--token "$(token_from_env)" \
		--org symphony
}

cmd_verify() {
	python3 scripts/verify_dashboards_live.py \
		--grafana "${GRAFANA_URL}" \
		--user admin --password "$(password_from_env)" --quiet
}

cmd_down() {
	docker compose down -v
}

cmd_logs() {
	docker compose logs -f grafana
}

case "${1:-up}" in
	up) cmd_up ;;
	seed) cmd_seed ;;
	verify) cmd_verify ;;
	down) cmd_down ;;
	logs) cmd_logs ;;
	*)
		echo "usage: $0 {up|seed|verify|down|logs}" >&2
		exit 2
		;;
esac
